### ISSUE TITLE
No initial states in update_steps

### ISSUE THREAD

**Issue by kkjh0723** [google-research/batch-ppo#19]
I'm not sure I understood correctly but it seems there is no initial state set in `_perform_update_steps` and `_update_step` in `Algorithm.py`

    '''in def _perform_update_steps()'''
    value = self._network(observ, length).value
    ...
    
    '''in def _update_step()'''
    network = self._network(observ, length)

While it is set in `perform` function,

    '''in def perform()'''
    output = self._network(observ[:, None], tf.ones(observ.shape[0]), state)

In the above two functions, are the initial states always set to zero? Is there any reason?

**Comment by danijar** [comment]
Sorry, I just saw this issue now. The network must create an initial state if no state was provided. The currently implemented recurrent policy network actually uses a zero state in this case, but other options would be possible (e.g. training a variable for the initial state). The reason for not providing a state during training is that training happens on whole sequences, so should start from an initial state.
