### ISSUE TITLE
Running out of GPU memory

### ISSUE THREAD

**Issue by wwxFromTju** [google-research/batch-ppo#21]
Hey all:

When I try to run the train.py, it take the all GPU memory, and I try to add per_process_gpu_memory_fraction, it can't work.

so how to change the GPU memory use?

**Comment by danijar** [comment]
PR #18 recently changed training on GPU. It is possible that it puts too many ops on the GPU. What tensors fails? What GPU do you use? Can you please set `use_gpu = False` in the config and verify that CPU-only training works?

**Comment by danijar** [comment]
@wwxFromTju Could you provide an update, please?

**Comment by wwxFromTju** [comment]
@danijar what update?

**Comment by danijar** [comment]
I asked a few questions in my first comment that could help debug your problem. Did you have a chance to try those?

**Comment by danijar** [comment]
I disabled GPU usage by default and implemented splitting episodes (using the `chunk_length` and `batch_size` config options) to be able to train on episodes with many time steps or large observations.
