### ISSUE TITLE
Support for discrete action spaces

### ISSUE THREAD

**Issue by dchichkov** [google-research/batch-ppo#22]
I'm trying to train an agent in a discrete environment space and I'm getting the following exception:
Is that by design?  If yes, any pointers onto changes required to make it work with discrete space?

```
ERROR:tensorflow:Error in environment process: Traceback (most recent call last):
  File "agents/tools/wrappers.py", line 445, in _worker
    env = constructor()
  File "/home/dchichkov/w/agents/agents/scripts/train.py", line 106, in <lambda>
    lambda: _create_environment(config),
  File "/home/dchichkov/w/agents/agents/scripts/train.py", line 52, in _create_environment
    env = tools.wrappers.RangeNormalize(env)
  File "agents/tools/wrappers.py", line 195, in __init__
    observ is not False and self._is_finite(self._env.observation_space))
  File "agents/tools/wrappers.py", line 251, in _is_finite
    return np.isfinite(space.low).all() and np.isfinite(space.high).all()
AttributeError: 'Discrete' object has no attribute 'low'

```

```
def copy():
  """Configuration for the copy task."""
  locals().update(default())
  # Environment
  env = 'Copy-v0'
  max_length = 200
  steps = 2e6  # 2M
  return locals()

```

**Comment by danijar** [comment]
Thank you for reporting this. We are adding support for discrete action spaces to PPO. I will provide an update once it is working.

**Comment by danijar** [comment]
PPO now uses TF distributions to represent policies, so that we can use the same algorithm for discrete action distributions. We are waiting for the CLA to be figured out of this pull request that enables training on environments with discrete actions: https://github.com/tensorflow/agents/pull/26

**Comment by danijar** [comment]
Discrete actions are supported as of #26.
