### ISSUE TITLE
Typo in Paper

### ISSUE THREAD

**Issue by pascalwhoop** [google-research/batch-ppo#23]
Hi,
I didn't know what is the best way to communicate but I think this will do, as the .tex is not in the repo.

In the linked paper, there is a typo. Just look for:

> A TensorFlow Agents algorithm defines the inference and learning computation
for of a batch of agents.

Between the "for" and the "off" there's something up

Also 

> The agents are represented as indices into the batch dimension.

I think that is "in" instead of "into"

> and returns an actions as a tensor with batch dimension

I think its *returns actions as a tensor with batch dimensions* ?

Sorry, if you don't care. I thought it's a preprint so correcting some typos would be welcomed. 

Thanks for the work by the way! I'll employ it in the next months in my thesis. 

P.S. What is the difference between your approach (using the TF graph) and the ELF approach using a separate C++ environment for multi-threading? Did the other team not want to use TF or are they having better Multithreading performance than your system? I posted the same question [on stackexchange](https://datascience.stackexchange.com/questions/26484/what-are-the-major-differences-between-facebooks-elf-rf-framework-and-tensorflo)

**Comment by danijar** [comment]
Hi @pascalwhoop, thanks for pointing out the typos. I will fix them in the next version.

I think both approaches are valid, although I would question that framework design is complicated by process-level parallelism in Python. It was surprisingly simple and all the process logic is implemented in an [ExternalProcess env wrapper](https://github.com/tensorflow/agents/blob/459c4f88ece996eac3489e6e97a6ee0b30bdd6b3/agents/tools/wrappers.py#L300). The C++ implementation could be faster, but we found implementing everything in TensorFlow to be simpler and work well.

By the way, TensorFlow Agents was developed at Google Brain, not DeepMind :)
