### ISSUE TITLE
Generalized advantage estimation

### ISSUE THREAD

**Issue by codegank** [google-research/batch-ppo#32]
Hi Danijar,

Recently, I was diving into the details of the code and have found some lines of code might be wrong.

1. In the file ppo.py lines 356-358, the function of computing advantage is given five inputs:
    `advantage = utility.lambda_advantage(
          reward, value, length, self._config.discount,
          self._config.gae_lambda)`,
    but in the file utility.py where defined this function only has four arguments.

2. In the file utility.py lines 89-90, the code of computing the return:
   `  return_ += discount ** window * tf.concat(
      [value[:, window:], tf.zeros_like(value[:, -window:]), 1])`,
  should it be:
   `  return_ += discount ** window * tf.concat(
      [value[:, window:], tf.zeros_like(value[:, -window:])], 1)` ?

**Comment by danijar** [comment]
Thanks a lot for pointing that out, @codegank. The `fixed_step_return()` and `lambda_advantage()` are not used really used right now and I didn't test them. Would you be interested in creating a PR with the fixes you suggest?

**Comment by codegank** [comment]
Hi Danijar, thanks for you reply, I will pull a PR later.

**Comment by DoxasticFox** [comment]
@danijar It's been 9 odd months since @codegank's last comment, and I agree with his suggestion, so I submitted a PR (#53) with his proposed fix.

Unfortunately, it looks like the build is failing. I don't think the failure is related to my change.

**Comment by danijar** [comment]
Thanks!
