### ISSUE TITLE
Errors about the regularizer term

### ISSUE THREAD

**Issue by chychen** [google-research/batch-ppo#44]
Dear Danijar,

Thanks for your great contribution, this repo help me learn a lot.
And I found some lines of code might be wrong.

in the file ppo.py lines 486~488 as below:

`entropy = policy.entropy()`
`if self._config.entropy_regularization:`
`____ policy_loss -= self._config.entropy_regularization * entropy`

the shape of entropy (batch_size, episode_length) and the shape policy_loss (batch_size,) are mismatched.
if I enable the entropy_regularization in config files, then it will cause an error:
`ValueError: Inconsistent shapes: saw (?,) but expected () (and infer_shape=True)`

I think the rank of entropy should be reduced before the subtraction:
`entropy = tf.reduce_mean(policy.entropy(), axis=1)`
`if self._config.entropy_regularization:`
`____ policy_loss -= self._config.entropy_regularization * entropy`

Thanks

**Comment by danijar** [comment]
Thank you for pointing this out. Would you be able to create a PR for us to integrate?

**Comment by danijar** [comment]
Fixed in #45
