### ISSUE TITLE
Minimal Example For TPU?

### ISSUE THREAD

**Issue by aidangomez** [google-research/batch-ppo#49]
Hey all,

Are there plans to support training on TPU? I use Cloud TPUs and would really appreciate an example of the correct way to do RL on TPUs. 

I imagine we would avoid TPUEstimator and use tf.Sessions along with tpu.rewrite directly, but I haven't seen any of this written down besides [tensorflow/minigo](https://github.com/tensorflow/minigo) which is a bit of a behemoth and not exactly a "minimal example".

Let me know your thoughts and feel free to email me directly.

**Comment by danijar** [comment]
I haven't used TPU myself yet so I don't have a minimal example that I could share. It should be possible to use TPUEstimator instead of the [current training loop](https://github.com/tensorflow/agents/blob/4b1485150adaefb03dbc03a63d7ca335da810499/agents/scripts/train.py#L122) though.

**Comment by aidangomez** [comment]
So how do you think we'd go about using TPUEstimator? It requires an input_fn and I'm not totally sure how we would incorporate a gym environment into that since the environment requires the predictions from the model_fn.

**Comment by danijar** [comment]
Closing as I don't have the capacity for this. Feel free to send a PR if you get it to work on TPU.
