### ISSUE TITLE
Maximum number of clients reachedSegmentation fault (core dumped)

### ISSUE THREAD

**Issue by louis030195** [google-research/batch-ppo#50]
Hi,

I'm trying to train my custom env (Xmoto game) with ppo, i get the following error after training about 2 hours and Phase eval (phase step 11100, global step 33900).

> Maximum number of clients reachedSegmentation fault (core dumped)

my config

```
def xmoto():
  """Configuration for Xmoto task."""
  locals().update(default())
  env = 'Xmoto-v0'
  use_gpu = False
  max_length = 10
  steps = 3e4
  update_every = 60
  network = networks.feed_forward_categorical
  return locals()
```

running tensorflow 1.12.0 (not gpu)
pc config: i7 6700HQ 16GB ram Ubuntu 18 04

ran with
> python3 -m batch-ppo-master.agents.scripts.train --config=xmoto --noenv_processes --logdir=models

Thanks for any help

**Comment by louis030195** [comment]
I noticed a memory leak, i guess that's why the training crashed, now i got to find why there is a memory leak

**Comment by danijar** [comment]
Thank you for working on this and please let me know if there are any details I can provide to help.

**Comment by louis030195** [comment]
Thank you, the problem is probably just that i don't have enough RAM / CPU is overloaded (i should start using GPU), i admitted that because i had the same issue with other algorithms

**Comment by danijar** [comment]
In that case, I would make sure that no other heavy applications are running and reduce the number of parallel agents in the configuration, for example `num_agents = 5` in configs.py.
