### ISSUE TITLE
How to draw the score curve of PPO?

### ISSUE THREAD

**Issue by AceChuse** [google-research/batch-ppo#52]
Hello,

I don't know how to draw the score curve PPO which in the paper of PPO? How to deal with the situation when the game is not over but the sample pool is full? In this cause if we end the game, it means that we cannot calculate the score which agent needs to perform more than Horizon (T) interactions with the environment to get, such as Walker2d-v1. But if we don't end the game when the sample pool is full, the number of samples maybe larger than Horizon (T).

I don't know how to deal with this problem. How do you deal with this problem in the PPO experiment? I really care about this. Thanks for your help.

**Comment by danijar** [comment]
I don't quite understand the question. What is the sample pool and what does it have to do with evaluating the agent? In reinforcement learning, we typically evaluate an agent by simulating multiple episodes until the end and average their scores. The environment determines how long these episodes are. In the PPO code, there is a configuration parameter `max_length` that should be set at least as large as the longest possible episodes. It's used for initializing the agent's episode memory for training.

**Comment by AceChuse** [comment]
I mean，it need to sample a minibatch of samples from environment before each training iter. But when we already get enough samples but the game is not over yet, how we should do during both training and evaluating. If we should save checkpoints every N steps and just use them to run evaluation, I understand how to do during evaluation. 

But how to deal with this problem during training? Such as breakout, there are 256 minibatch each iter in Atari game which are introduced in PPO paper. However, 256 steps are not enough for the agent to run to the end of the game. Do we need to save the game if it is not end and start again at save point after this training iter?

**Comment by danijar** [comment]
The agent collects multiple episodes and then samples many smaller mini-batches from the stored transitions for training. As a result, the mini-batch size can be smaller than the number of steps collected for each update phase (but not larger). For exact implementation details of the PPO agent that OpenAI used in their paper, you might want to check out their code instead.

**Comment by AceChuse** [comment]
Sorry, I didn't find that you have already replied to me. I think I may not understand what you mean. The way you said to get mini-batches seems to be the method used in DQN. Isn't it to perform an update after N interactions with the environment using the current strategy? What I mean N is the steps per epoch. I'm sorry use minibatch to denote it, it makes confuse. What I want to know is if the steps per epoch is lower than the steps per game needed to end.

For example, if the  steps per epoch is 256 and the game is now 256 steps, what should we do? If I use the PPO algorithm we should update the model now. So should I end the game and reset it? If I end the game, agent cannot get the sample after 256 steps. I don't know how to deal with this problem.

**Comment by danijar** [comment]
You can set the epoch size larger than the maximum length of the game to avoid this issue.

**Comment by AceChuse** [comment]
Oh, I see. Thank you for your help!
