### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [google-research/batch-ppo#56]
Hello,I found a performance issue in google-research/batch-ppo/blob/master/agents/parts/iterate_sequences.py ,[dataset = dataset.map](https://github.com/google-research/batch-ppo/blob/3d09705977bae4e7c3eb20339a3b384d2a5531e4/agents/parts/iterate_sequences.py#L57) was called without **num_parallel_calls**.I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by danijar** [comment]
Thanks for sharing this! However, we're not maintaining this codebase anymore so there will be no changes, but feel free to fork it and apply the changes there.
