### ISSUE TITLE
Performance issue in agents/parts/iterate_sequences.py

### ISSUE THREAD

**Issue by DLPerf** [google-research/batch-ppo#57]
Hello, I've found a performance issue in "agents/parts/iterate_sequences.py": `dataset = dataset.batch(batch_size or num_sequences)`[(here)](https://github.com/google-research/batch-ppo/blob/3d09705977bae4e7c3eb20339a3b384d2a5531e4/agents/parts/iterate_sequences.py#L66) should be called before `dataset = dataset.map(remove_padding).flat_map`[(here)](https://github.com/google-research/batch-ppo/blob/3d09705977bae4e7c3eb20339a3b384d2a5531e4/agents/parts/iterate_sequences.py#L57) which would make your program more efficient. Moreover, `length = sequence.pop('length')`[(here)](https://github.com/google-research/batch-ppo/blob/3d09705977bae4e7c3eb20339a3b384d2a5531e4/agents/parts/iterate_sequences.py#L126) indicates that the function `remove_padding`[(here)](https://github.com/google-research/batch-ppo/blob/3d09705977bae4e7c3eb20339a3b384d2a5531e4/agents/parts/iterate_sequences.py#L113) isn't vectorized. To call `dataset = dataset.batch(batch_size or num_sequences)` before `dataset = dataset.map(remove_padding).flat_map`, `remove_padding` is supposed to be vectorized. Can `remove_padding` be vectorized? The performance of your code could be further improved if it can.

Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
Hello, I'm looking forward to your reply~

**Comment by danijar** [comment]
Thanks for the suggestions! The code is in archived state, so I won't make those changes. But please feel free to fork it and create a better version if you like.
