### ISSUE TITLE
Different frames error when adding another RNNCell

### ISSUE THREAD

**Issue by haoliuhl** [google-research/batch-ppo#6]
I have two different neural networks, both inherit tf.contrib.rnn.RNNCell, say `a = net_1(s)` and `scal = net_2(s,a)`, `net_1(s)` is exactly the policy network defined in networks, and `net_2(s,a)` is a similiar network takes both a and s as input.  I want to do some tf.scan operation to update `net_2` which includes some loss conditioned on both neural networks' outputs, say `loss = a - scal`. Doing this throws an error: 

    tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'end_episode/cond/cond/training/update_policy/scan_1/while/policy_loss/ExpandDims_2/Switch' has inputs from different frames. The input 'simulate/cond_2/pred_id' is in frame ''. The input 'end_episode/cond/cond/training/update_policy/scan_1/while/policy_loss/cfnetwork/rnn/while/steincf/gradients/end_episode/cond/cond/training/update_policy/scan_1/while/policy_loss/cfnetwork/rnn/while/steincf/Flatten_1/Reshape_grad/Reshape' is in frame 'end_episode/cond/cond/training/update_policy/scan_1/while/policy_loss/cfnetwork/rnn/while/end_episode/cond/cond/training/update_policy/scan_1/while/policy_loss/cfnetwork/rnn/while/'.

It states that in `loss = a - scal`, `a` is in frame '' while `scal` is its while frame.

I searched google but did not find any problems like this, so I am not sure if it is a bug or something others, could anyone help me figure out this problem?

**Comment by danijar** [comment]
The problem might be that you define the networks first with a control flow statement. To ensure that you're variables are accessible from anywhere, call your network once in the constructor, as done in the PPO implementation for the existing network. If that doesn't help, maybe you can structure your code to only use one RNNCell that wraps the two other cells.

**Comment by danijar** [comment]
Closed due to inactivity.
